/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 SkodaSuperb.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/SkodaSuperb.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-7.194, 0.02, -10.327]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={1.226}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 69.208, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group position={[0, 0, -0.001]}>
              <group position={[0, 0.891, 0.333]}>
                <mesh geometry={nodes.bonnet_ok_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.bonnet_ok001_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.bonnet_ok001_wheel1_0.geometry} material={materials['wheel.1']} />
              </group>
              <group position={[0, -2.082, 0.443]}>
                <mesh geometry={nodes.boot_ok_boot_ok12_0.geometry} material={materials['boot_ok.12']} />
                <mesh geometry={nodes.boot_ok_bump_front_ok7_0.geometry} material={materials['bump_front_ok.7']} />
                <mesh geometry={nodes.boot_ok_bump_front_ok8_0.geometry} material={materials['bump_front_ok.8']} />
                <mesh geometry={nodes.boot_ok_bump_front_ok9_0.geometry} material={materials['bump_front_ok.9']} />
                <mesh geometry={nodes.boot_ok_chassis4_0.geometry} material={materials['chassis.4']} />
                <mesh geometry={nodes.boot_ok_interior1_0.geometry} material={materials['interior.1']} />
                <mesh geometry={nodes.boot_ok_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.boot_ok_left_front_light_0.geometry} material={materials['left_front_light.002']} />
                <mesh geometry={nodes.boot_ok_lights10_0.geometry} material={materials['lights.10']} />
                <mesh geometry={nodes.boot_ok_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.boot_ok_right_rear_light_0.geometry} material={materials.right_rear_light} />
                <mesh geometry={nodes.boot_ok_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.boot_ok_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.boot_glass_ok_glass001_0.geometry} material={materials['glass.004']} />
              </group>
              <group position={[0, 2.26, -0.228]}>
                <mesh geometry={nodes.bump_front_ok_bump_front_ok10_0.geometry} material={materials['bump_front_ok.10']} />
                <mesh geometry={nodes.bump_front_ok_bump_front_ok7_0.geometry} material={materials['bump_front_ok.7']} />
                <mesh geometry={nodes.bump_front_ok_bump_front_ok8_0.geometry} material={materials['bump_front_ok.8']} />
                <mesh geometry={nodes.bump_front_ok_bump_front_ok9_0.geometry} material={materials['bump_front_ok.9']} />
                <mesh geometry={nodes.bump_front_ok_chassis6_0.geometry} material={materials['chassis.6']} />
                <mesh geometry={nodes.bump_front_ok_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.bump_front_ok_left_front_light_0.geometry} material={materials['left_front_light.002']} />
                <mesh geometry={nodes.bump_front_ok_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.bump_front_ok_right_front_light_0.geometry} material={materials.right_front_light} />
                <mesh geometry={nodes.bump_front_ok_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.bump_front_ok_wheel3_0.geometry} material={materials['wheel.3']} />
                <mesh geometry={nodes.bump_front_ok001_glass003_0.geometry} material={materials['glass.005']} />
              </group>
              <group position={[0, 0, 0.001]}>
                <group position={[0.027, 1.173, -0.06]}>
                  <mesh geometry={nodes.enginebay_enginebay1_0.geometry} material={materials['enginebay.1']} />
                  <mesh geometry={nodes.enginebay_enginebay2_0.geometry} material={materials['enginebay.2']} />
                  <mesh geometry={nodes.enginebay_enginebay3_0.geometry} material={materials['enginebay.3']} />
                  <mesh geometry={nodes.enginebay_enginebay4_0.geometry} material={materials['enginebay.4']} />
                  <mesh geometry={nodes.enginebay_enginebay5_0.geometry} material={materials['enginebay.5']} />
                  <mesh geometry={nodes.enginebay_enginebay6_0.geometry} material={materials['enginebay.6']} />
                  <mesh geometry={nodes.enginebay_wheel1_0.geometry} material={materials['wheel.1']} />
                </group>
                <mesh geometry={nodes.chassis_chassis4_0.geometry} material={materials['chassis.4']} />
                <mesh geometry={nodes.chassis_chassis5_0.geometry} material={materials['chassis.5']} />
                <mesh geometry={nodes.chassis_chassis6_0.geometry} material={materials['chassis.6']} />
                <mesh geometry={nodes.chassis_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.chassis_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.chassis_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.chassis_wheel3_0.geometry} material={materials['wheel.3']} />
                <mesh geometry={nodes.interior_interior1_0.geometry} material={materials['interior.1']} />
                <mesh geometry={nodes.interior_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.interior_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.lights_glass_0.geometry} material={materials['glass.002']} />
                <mesh geometry={nodes.lights_interior1_0.geometry} material={materials['interior.1']} />
                <mesh geometry={nodes.lights_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.lights_lights10_0.geometry} material={materials['lights.10']} />
                <mesh geometry={nodes.lights_lights6_0.geometry} material={materials['lights.6']} />
                <mesh geometry={nodes.lights_lights7_0.geometry} material={materials['lights.7']} />
                <mesh geometry={nodes.lights_right_front_light_0.geometry} material={materials.right_front_light} />
                <mesh geometry={nodes.lights_right_rear_light_0.geometry} material={materials.right_rear_light} />
                <mesh geometry={nodes.lights_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.lights_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.lights_wheel3_0.geometry} material={materials['wheel.3']} />
                <mesh geometry={nodes.indicators_glass_0.geometry} material={materials['glass.002']} />
                <mesh geometry={nodes.lights_glass_glass001_0.geometry} material={materials['glass.004']} />
                <mesh geometry={nodes.lights_glass_glass002_0.geometry} material={materials['glass.003']} />
              </group>
              <group position={[-0.853, 0.883, 0.029]}>
                <mesh geometry={nodes.door_lf_ok_enginebay5_0.geometry} material={materials['enginebay.5']} />
                <mesh geometry={nodes.door_lf_ok_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.door_lf_ok_lights7_0.geometry} material={materials['lights.7']} />
                <mesh geometry={nodes.door_lf_ok_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.door_lf_ok_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.door_lf_ok001_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.door_lf_ok002_glass002_0.geometry} material={materials['glass.003']} />
                <mesh geometry={nodes.door_lf_ok002_glass005_0.geometry} material={materials['glass.007']} />
              </group>
              <group position={[-0.872, -0.288, -0.057]}>
                <mesh geometry={nodes.door_lr_ok_enginebay5_0.geometry} material={materials['enginebay.5']} />
                <mesh geometry={nodes.door_lr_ok_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.door_lr_ok_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.door_lr_ok_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.door_lr_ok001_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.door_lr_ok002_glass004_0.geometry} material={materials['glass.006']} />
              </group>
              <group position={[0.853, 0.884, 0.03]}>
                <mesh geometry={nodes.door_rf_ok_enginebay5_0.geometry} material={materials['enginebay.5']} />
                <mesh geometry={nodes.door_rf_ok_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.door_rf_ok_lights6_0.geometry} material={materials['lights.6']} />
                <mesh geometry={nodes.door_rf_ok_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.door_rf_ok_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.door_rf_ok001_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.door_rf_ok002_glass002_0.geometry} material={materials['glass.003']} />
                <mesh geometry={nodes.door_rf_ok002_glass005_0.geometry} material={materials['glass.007']} />
              </group>
              <group position={[0.872, -0.288, -0.057]}>
                <mesh geometry={nodes.door_rr_ok_enginebay5_0.geometry} material={materials['enginebay.5']} />
                <mesh geometry={nodes.door_rr_ok_interior2_0.geometry} material={materials['interior.2']} />
                <mesh geometry={nodes.door_rr_ok_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.door_rr_ok_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.door_rr_ok001_primary_0.geometry} material={materials['primary.001']} />
                <mesh geometry={nodes.door_rr_ok002_glass004_0.geometry} material={materials['glass.006']} />
              </group>
              <group position={[0, 0.815, 0.508]}>
                <mesh geometry={nodes.windows_glass004_0.geometry} material={materials['glass.006']} />
                <mesh geometry={nodes.windows_glass006_0.geometry} material={materials['glass.008']} />
              </group>
            </group>
            <group position={[0.768, 1.327, -0.333]} rotation={[-0.001, 0, 0]}>
              <group position={[-0.012, 0, -0.015]} rotation={[0.001, 0, 0]}>
                <mesh geometry={nodes.wheel_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.wheel_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.wheel_wheel2_0.geometry} material={materials['wheel.2']} />
                <mesh geometry={nodes.wheel_wheel3_0.geometry} material={materials['wheel.3']} />
                <mesh geometry={nodes.wheel_wheel4_0.geometry} material={materials['wheel.006']} />
              </group>
              <group position={[-0.012, -2.857, -0.038]} rotation={[0.001, 0, 0]}>
                <mesh geometry={nodes.wheel001_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.wheel001_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.wheel001_wheel2_0.geometry} material={materials['wheel.2']} />
                <mesh geometry={nodes.wheel001_wheel3_0.geometry} material={materials['wheel.3']} />
                <mesh geometry={nodes.wheel001_wheel4_0.geometry} material={materials['wheel.006']} />
              </group>
              <group position={[-1.526, 0, -0.015]} rotation={[-3.141, 0, 0]} scale={-1}>
                <mesh geometry={nodes.wheel002_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.wheel002_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.wheel002_wheel2_0.geometry} material={materials['wheel.2']} />
                <mesh geometry={nodes.wheel002_wheel3_0.geometry} material={materials['wheel.3']} />
                <mesh geometry={nodes.wheel002_wheel4_0.geometry} material={materials['wheel.006']} />
              </group>
              <group position={[-1.526, -2.857, -0.038]} rotation={[-3.141, 0, 0]} scale={-1}>
                <mesh geometry={nodes.wheel003_wheel0_0.geometry} material={materials['wheel.0']} />
                <mesh geometry={nodes.wheel003_wheel1_0.geometry} material={materials['wheel.1']} />
                <mesh geometry={nodes.wheel003_wheel2_0.geometry} material={materials['wheel.2']} />
                <mesh geometry={nodes.wheel003_wheel3_0.geometry} material={materials['wheel.3']} />
                <mesh geometry={nodes.wheel003_wheel4_0.geometry} material={materials['wheel.006']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/SkodaSuperb.glb')
